LACMTA/realtime-map

- README.md
- index.html
- index2.html
- Added brt lines
- Updated project name to Metro Realtime Map
- Refactored mobile responsiveness
The purpose of this pull request is to update the project name to "Metro Realtime Map" and improve the mobile responsiveness of the application. These changes will enhance the user experience and make the application more accessible on different devices.
Please review the changes and provide any feedback or suggestions. Thank you!
> Update project name and improve mobile responsiveness

- index.html
This pull request addresses several issues related to geolocation functionality and improves overall performance. The following changes are included:
- Fixed geolocation functionality to ensure accurate location data.
- Improved performance by optimizing code and removing unnecessary dependencies.
- Added a geolocation button for easier access to location services.
- Refactored code to remove the BRT (Binary Runtime) library, resulting in a more streamlined codebase.
- Fixed issues with the geolocate button for smoother user experience.
These changes aim to enhance the geolocation feature and provide a more efficient and reliable user experience. No files or commits are listed in this description for brevity.
> Fix geolocation issues and improve performance

- index.html
This pull request includes changes to the map styling and adds an update time element to the map. The map styling has been updated to improve visibility and aesthetics. The update time element displays the time of the last update on the map. These changes enhance the user experience and provide more information to the users.
> Update map styling and add update time element

- index.html
This pull request fixes a bug in the index.html file where the animation was not completing properly. The bug caused the markers to not be removed from the map after the animation was complete. This PR adds a condition to check if the animation is complete and removes the marker from the map if it is. Additionally, the marker is deleted from the markers object. This ensures that the markers are properly removed from the map and prevents any memory leaks.
> Fix animation completion bug in index.html

- index.html
This pull request removes unnecessary CSS and markers from the codebase. The changes include removing the `.pulsatingIcon` CSS class and its associated animation, as well as removing markers that are not present in the new data. These changes improve the codebase by reducing unnecessary code and improving performance.
> Refactor: Remove unnecessary CSS and markers

- index.html
This pull request fixes a bug related to marker removal and adds functionality to convert the current time to PST.
The bug fix ensures that markers are properly removed from the map when they are not present in the new data.
These changes improve the overall functionality and accuracy of the application.
> Fix marker removal bug and convert time to PST

- basemap.html
- index.html
This pull request updates the maplibre.gl library to the latest version and increases the timeout for loading data to 25 seconds. This ensures better compatibility and allows for more time to retrieve data in case of slow connections.
> Update maplibre.gl to latest version and increase timeout to 25 seconds

- basemap.html
- index.html
refactor: timeout to 25 seconds
> feat: updated maplibre.gl to latest version

- index.html
- Fixed the timestamp issue
- Refactored the fetchData function
- Refactored the clearing of the "loading" variable to only occur if markers are greater than 1
- Added initial page loading of data
> Fix timestamp issue

- basemap.html
- index.html
This pull request includes the following commits:
- fix: timestamp issue
- refactor: new `fetchData` function
- refactor: `loading` now cleared only if markers are greater than `1`
- feat: initial page loading of data
- Merge pull request #24 from LACMTA:post-1-0-enhancements
The fix: timestamp issue commit addresses a timestamp issue in the code. The refactor: new `fetchData` function commit introduces a new function for fetching data. The refactor: `loading` now cleared only if markers are greater than `1` commit refactors the code to clear the loading state only if there are more than one markers. The feat: initial page loading of data commit adds a feature for initial page loading of data. Finally, the Merge pull request #24 from LACMTA:post-1-0-enhancements commit merges the changes …
> Fix timestamp issue and refactor fetchData function

- index.html
This pull request refactors the error handling in the fetchData function. It adds specific error messages based on the type of error encountered, providing more informative feedback to the user.
> Refactor error handling in fetchData function

- index.html
This pull request includes a refactor of the loading animation and error handling. The loading animation has been updated to use CSS keyframes for smoother transitions. Additionally, error handling has been improved to provide more specific error messages and handle different types of errors.
> Refactor loading animation and error handling

- railbrt.html
This pull request adds the code for the railbrt.html file.
> Add railbrt.html code

- bus.html
> feat: added vector tiles support for bus.html

- index.html
Fixes:
- animation resizing for markers so they stay the same size
- cache busting so the data is always fresh.
Features:
- refresh button
This pull request includes a code refactor that improves the performance and readability of the codebase. The changes made in this pull request aim to optimize the code and make it easier to understand and maintain.
> Refactor code for improved performance and readability

- bus.html
This pull request adds parameterized routes for the bus map feature, allowing users to search for specific bus routes and view their details.
> Parameterized routes for bus map

- bus.html
This pull request adds support for route parameters in the fetchData function. It also updates the createRouteSelect function to set the selected option of the route-select element based on the route parameter in the URL.
> Add route parameter support

- bus.html
This pull request adds a z-index property to the dropdown menu items in order to ensure that they appear above other elements on the page.
> Add z-index to dropdown menu items

- bus.html
This pull request refactors the fetchData function and adds a new function clearAllMarkersAndFetchNew. The fetchData function now accepts a route parameter and the clearAllMarkersAndFetchNew function clears all markers and fetches new data based on the selected route. This improves the code structure and enhances the functionality of the application.
> Refactor fetchData function and add clearAllMarkersAndFetchNew function

- bus.html
- index.html
This pull request refactors the code to hide the alert message. The alert message is now hidden using JavaScript.
> Refactor: Hide alert and improve map loading

- websocket.html
- websocket.js
This pull request fixes a bug in the websocket functionality. The bug was causing intermittent connection issues and unexpected behavior.
> feat: bouncy buggy websocket

- websocket.js
This pull request fixes a bug in the logic where the marker rotations were not being updated in the websocket.
> Update Marker Rotations

- websocket.html
- websocket.js
This pull request fixes the marker size and position in the WebSocket code. The changes include updating the marker size and position based on the zoom level, adding a background-position property to the marker, and setting the transform origin to the center of the marker.
> Fix marker size and position in WebSocket code

- index.html
This pull request adds a heading for debugging purposes. The heading displays the position bearing of the vehicle.
> Add heading for debugging

- index.html
This pull request includes two commits:
1. feat: rounded bearing
2. feat: filter out data by time no older than 15 minutes
The changes in the code include:
- Adding a rounded bearing for markers
- Filtering out data by time, only including data that is no older than 15 minutes
These changes improve the accuracy and presentation of the data in the application.
> Add rounded bearing and filter out data by time

- debug.html
- websocket.js
This pull request refactors the code related to marker rotation and updates the content of the popup displayed when clicking on a marker. The changes include:
- Refactoring the `updateExistingMarker` function to improve performance and readability.
- Updating the `updatePopup` function to display the correct vehicle ID and timestamp.
- Modifying the `createNewMarker` function to rotate the marker based on the heading and update the popup content.
- Updating the `updateMarkerRotations` function to correctly calculate the marker rotation based on the map's bearing.
These changes improve the overall user experience and make the code more maintainable.
> Refactor marker rotation and update popup content

- arrow.svg
- websocket.js
- Added arrow.svg file
- Refactored the popup function to display an image and a line label instead of just the vehicle ID.
> Add arrow.svg and refactor popup

- websocket.js
This pull request refactors the vehicle marker animation and removal logic. It includes changes to the `processAndUpdate` function, `setupWebSocket` function, `removeOldMarkers` function, and `processVehicleData` function. The changes optimize the code by removing unnecessary requests and improving the efficiency of marker removal.
> Refactor vehicle marker animation and removal logic

- index.html
This pull request fixes the title and styling in the index.html file. The title was changed from "Metro - Live Rail Map" to "Metro Live Map" and the styling of the beta badge was updated to have a white text color, orange background color, smaller font size, padding, and rounded corners.
> Fix title and styling in index.html

- websocket.js
This pull request refactors the WebSocket setup and adds filtering for vehicle IDs. It also updates the WebSocket URLs to use the correct endpoints.
> Refactor WebSocket setup and add filtering for vehicle IDs

- index-old-2024-02-13.html
- index.html
- websocket.js
This pull request includes a fix for the websocket data, which is now coming in as individual rows. It also includes a refactoring of the home button styling and the removal of unused code.
> Fix websocket data and refactor home button styling

- websocket.js
- Fixed formatting code spacing to improve performance and readability
- Added websockets feature to the project.
> Release v1.1 with websockets support

- bus.html
- websocket.js
This pull request includes two commits. The first commit clears old data after 2 minutes to ensure that only fresh data is displayed. The second commit fixes the marker size to a constant value of 40 pixels.
> Clear old data after 2 minutes and fix constant marker size

- debug.html
- index.html
- websocket-debug.js
- Fixed the background color hover effect to the home icon.
- Added a new debug.html page.
> Fix background color hover effect to home icon and add debug.html page

- websocket.js
This pull request refactors the map center and pitch values to improve the user experience. The center coordinates have been updated to [-118.25133692966446, 34.00095151499077] and the pitch value has been set to 0. Additionally, the zoom level is now dynamically adjusted based on the screen width.
> Refactor map center and pitch

- websocket-debug.js
This pull request removes the speed property from the vehicle display in order to simplify the UI and improve performance.
> Remove speed property from vehicle display

- websocket.js
This pull request adds the ability to pass zoom parameters in the URL and sets the zoom level based on the screen width. This allows for more flexibility in controlling the initial zoom level of the map.
> Add zoom params and zoom level based on screen width

- websocket.js
This pull request reduces the retention period to 3 minutes and adds a cleanup function to remove old markers. This ensures that the features array and markers object only contain up-to-date data.
> Reduce retention period and add cleanup function

- websocket.js
This pull request refactors the WebSocket.js file and adds a cleanup functionality to remove markers and animations that are older than three minutes. This improves the performance and memory usage of the application.
> Refactor WebSocket.js and add cleanup functionality

- websocket.js
This pull request refactors the cleanupData() function to handle pending data when the document is not visible. It adds a check for document visibility and clears any pending data if the document is not visible. This ensures that data is properly handled and prevents any potential issues when the document is not in focus.
> Refactor cleanupData() function to handle pending data when document is not visible

- websocket.js
This pull request includes two commits:
1. Refactor: processVehicleData function to skip outdated vehicle data
2. Refactor: vehicle marker creation logic in websocket.js
The changes in this pull request improve the efficiency and accuracy of the processVehicleData function by skipping outdated vehicle data. Additionally, the vehicle marker creation logic in websocket.js has been refactored to handle cases where a marker with the same vehicle_id already exists.
> Refactor processVehicleData function and vehicle marker creation logic

- bus.html
- index.html
GA code added to `index.html` and `bus.html`
> add google analytics

- index.html
This pull request adds the Siteimprove analytics script to the `index.html` file.
> Add Siteimprove analytics script

- styles/index-style.css
- websocket.js
This pull request refactors the z-index for the attribution and WebSocket code. It updates the z-index for the attribution to be behind the legend and modifies the WebSocket code for handling the remove markers and animation issue.
> Refactor z-index for attribution and WebSocket code

- websocket.js
This pull request updates the logic for updating popups in the websocket.js file. It introduces a new interval to refresh the popup content every second and adds a function to calculate the time since the last update. This improves the accuracy and responsiveness of the popups in the application.
> Update popup logic in websocket.js

- styles/index-style.css
- websocket.js
> Feat: Last seconds update for popup

- websocket.js
This pull request refactors the vehicle data processing function and updates the marker update text from `data` to `location`.
> Refactor vehicle data processing and marker update

- websocket.js
This pull request refactors the marker cleanup function to remove markers and animations that are older than 1 minute. It also removes old entries from the features array and updates the retention period to 1 minute.
> Refactor marker cleanup function

- websocket.js
This pull request refactors the error message in the websocket.js file by commenting out the existing error message and adding a new one.
> Refactor error message in websocket.js

- index.html
- websocket.js
This pull request removes the legend description in the index.html file. The previous description was updated to check vehicle_ids and added vehicle ids back into the pop-up. Additionally, the `location from (x) seconds ago` pop-up was undone. This change improves the code by removing unnecessary information and simplifying the user interface.
> Refactor legend description in index.html

- index.html
- websocket.js
This pull request includes several refactorings to improve the legend description and pop-up functionality. The changes involve removing the legend description in the index.html file and updating the processing marker function to check vehicle_ids. Additionally, the vehicle ids have been added back into the pop-up and the `location from (x) seconds ago` pop-up has been undone. These changes were made based on feedback from Alex and John.
> Refactor legend description and pop-up functionality

- websocket.js
This pull request refactors the loading timeout message in the code to provide a more user-friendly message. It also adds a refresh functionality to allow users to easily refresh the page if the loading times out.
> Refactor loading timeout message and add refresh functionality

- index.html
- lightbulb.svg
This pull request adds a lightbulb icon to the share link in the legend section. The icon is displayed next to the "Share your thoughts!" text.
> Add lightbulb icon

- websocket.js
This pull request refactors the vehicle label in the popup to display either "Bus ID" or "Train Car #" based on the route code. This improves the clarity and accuracy of the information displayed in the popup.
> Refactor vehicle label in popup

- websocket.js
This pull request fixes a loading error in the processVehicleData() function and updates the marker in the same function.
This closes #116
> Fix loading error and update marker in processVehicleData() function
